# Molecule managed

---
all:
  hosts:
    centos: &id001
      ansible_connection: docker
    instance: &id002
      ansible_connection: docker
ungrouped:
  hosts:
    centos: *id001
    instance: *id002
  vars: {}
